version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.13.1
    commands:
      - npm cache clean --force
      - apt-get -y update
      - apt-get --assume-yes install chromium-browser
      - npm install --unsafe-perm
      - npm install babel-cli cross-env webpack-cli --global
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
cache:
  paths:
    - './node_modules/**/*'
