name: Main CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3

      - name: .env setting
        run: |
          echo "REACT_APP_THREADS_APP_ID=${{ secrets.REACT_APP_THREADS_APP_ID }}" >> .env
          echo "REACT_APP_THREADS_API_SECRET=${{ secrets.REACT_APP_THREADS_API_SECRET }}" >> .env
          echo "REACT_APP_THREADS_REDIRECT_URL=${{ secrets.REACT_APP_THREADS_REDIRECT_URL }}" >> .env
          echo "REACT_APP_THREADS_GRAPH_API_BASE_URL=${{ secrets.REACT_APP_THREADS_GRAPH_API_BASE_URL }}" >> .env
          echo "REACT_APP_THREADS_SESSION_SECRET=${{ secrets.REACT_APP_THREADS_SESSION_SECRET }}" >> .env
          echo "REACT_APP_SUPABASE_URL=${{ secrets.REACT_APP_SUPABASE_URL }}" >> .env
          echo "REACT_APP_SUPABASE_ANON_KEY=${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}" >> .env

      - name: npm install
        run: |
          npm cache clean --force
          npm install --unsafe-perm
          npm install babel-cli cross-env webpack-cli babel-runtime --global
          npm install --save-dev @babel/types

      - name: build
        run: CI=false npm run build

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            ./build s3://ktestweb

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v1
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: '/*'
          AWS_REGION: 'ap-northeast-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
